### ISSUE TITLE
The pretrain ckpts choice for classification and segmentation task

### ISSUE THREAD

**Issue by Amazingren** [qizekun/ReCon#16]
Dear @qizekun ,

Thanks for your very nice work, recently I noticed that reproducing the results for point cloud pretraining, usually, requires a decent pre-trained checkpoint.

My question is if the same pre-trained checkpoints are used for both the classification and the segmentation task.

For example, if I found ckpt-ep250 works well for classification, am i right to use it also for part segmentation? Or to produce also a decent result of part segmentation, I need to choose another ckpts (e.g., ckpt-ep300)
?

Thanks in advance for your answer.

Best regards and have a nice day,

**Comment by qizekun** [comment]
Thanks for your attention.

Yes, we use the same pre-trained checkpoint for both the classification and the segmentation task (the best for classification).

**Comment by Amazingren** [comment]
> Thanks for your attention.
> 
> Yes, we use the same pre-trained checkpoint for both the classification and the segmentation task (the best for classification).

Thanks for the quick feedback. It helped a lot. :)

With warm regards,
