### ISSUE TITLE
How to render the point cloud into rgb images?

### ISSUE THREAD

**Issue by Amazingren** [qizekun/ReCon#17]
Hi @RunpeiDong,

Thanks for your impressive work again.

Regarding the RGB images used in your work, may I ask how you render the point cloud into RGB images?

Are there any tools you suggested or which code base you used for this?

Best regards and many thanks,

**Comment by RunpeiDong** [comment]
Hi @Amazingren,

we use https://github.com/qizekun/PointVisualizaiton

Please check it out. For some visualization that requires special RGB (feature attention for example) we can also write ply files and use meshlab for visualization.

**Comment by Amazingren** [comment]
您的来信已经收到，稍后进行回复，谢谢~

**Comment by Amazingren** [comment]
> Hi @Amazingren,
> 
> we use https://github.com/qizekun/PointVisualizaiton
> 
> Please check it out. For some visualization that requires special RGB (feature attention for example) we can also write ply files and use meshlab for visualization.

Thanks for the quick feedback, this is really a nice tool for visualization.

One more question, how do you get the shapenet_img (shown below) from the shapnet point cloud data? 

![image](https://github.com/qizekun/ReCon/assets/31409716/999ff31c-d760-4b0d-9eea-7d49aeea349f)

**Comment by qizekun** [comment]
Hi,

We use MacOS's preview (quick look) to generate high-quality images.
You can use 'qlmanage' command in bash.

**Comment by Amazingren** [comment]
> Hi,
> 
> We use MacOS's preview (quick look) to generate high-quality images. You can use 'qlmanage' command in bash.

Cool, good to know!  Thanks again!
