### ISSUE TITLE
Zero-shot classification of ModelNet40

### ISSUE THREAD

**Issue by kaimingkuang** [qizekun/ReCon#2]
Thanks for your amazing work! I was trying to run zero-shot classification of ModelNet40 using the pipeline you provided. However, I only got 61.2% accuracy (66.8% reported in the paper) using the following script:
```bash
python main.py \
--config=cfgs/zeroshot/modelnet40.yaml \
--zeroshot \
--exp_name=zeroshot_modelnet \
--ckpts=ckpts/zeroshot_66_78.pth
```
Am I missing something here? Thanks!

**Comment by qizekun** [comment]
Have you made any modifications to the config file or model? We retested and achieved 66.7751% zero-shot performance. We upload the log file to https://drive.google.com/file/d/1GgKasd2f-4S_FCuIXj2MtNtsnV8dQu5-/view?usp=share_link
