### ISSUE TITLE
About pretain logs file

### ISSUE THREAD

**Issue by kengkeng1** [qizekun/ReCon#3]
Thanks for your amazing work! Can you provide the pretain logs file.I want to check if I'm running it incorrectly.
Thank you!

**Comment by RunpeiDong** [comment]
Hi @kengkeng1,

Sorry, we have not saved the pretrain logs as it was trained on some temporary servers. However, since it may be a help to you, we will rerun the pertaining process and provide a log for reference recently when we have time.

**Comment by qizekun** [comment]
Thanks for your kind attention! I'm so sorry for the late reply. We retrain the model and upload the log file into google drive (https://drive.google.com/file/d/1Ttk8b6uaOOOXYVAd6tDr8fQeqTuFLIrn/view?usp=drive_link). You can test the 250/275/300 epoch checkpoints for the best performance.
