### ISSUE TITLE
About ShapeNet55/34 Dataset

### ISSUE THREAD

**Issue by changshuowang** [qizekun/ReCon#5]
Thank you so much for your excellent work. When I run the pre-training code `sh scripts/pretrain.sh <GPU> <exp_name>,` I get an error，as shown：

> [ WARN:0@188.332] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/media/data/data01/wcs/data/ShapeNet55-34/shapenet_img/02747177-.png'): can't open/read file: check file path/integrity

I'm pretty sure it's a problem with the shapenet55/34 dataset. As you said “the image data is different from the pointcloud data in some samples, you need to update the meta-data "ShapeNet55-34/ShapeNet-55/train.txt & test.txt" from [Our Google Drive](https://drive.google.com/drive/folders/1ScKJpZbHh7VOqv0BebcRhcDc-JpJxJLd?usp=share_link).”

But i don't know what modification i need to do, can you tell me. Thanks.

**Comment by qizekun** [comment]
Hi, @changshuowang!

We have provided our meta-data in Google Drive(https://drive.google.com/drive/folders/1ScKJpZbHh7VOqv0BebcRhcDc-JpJxJLd). You need to unzip ShapeNet-55.zip and update the original ShapeNet-55/train.txt and ShapeNet-55/test.txt file.

**Comment by changshuowang** [comment]
@qizekun Thanks, thanks for your help, the problem has been solved now.
