### ISSUE TITLE
hello，how I run my own dataset？

### ISSUE THREAD

**Issue by Everglowever** [qizekun/ReCon#7]
When i try run own dataset，this error appears：dataset name  is not in the dataset registry'

**Comment by qizekun** [comment]
Hi, you need to add `@DATASETS.register_module()` before your own dataset class to register the dataset. Just like [this line](https://github.com/qizekun/ReCon/blob/f13a328e307adbbcceaed6b000c8cf033f790b18/datasets/ShapeNet55Dataset.py#L13C7-L13C7)

**Comment by Everglowever** [comment]
![image](![image](https://github.com/qizekun/ReCon/assets/50161052/804acc6e-99c3-48dd-af4a-a00d07bb248d))
Yes，I write this line，but this error also appears。

**Comment by qizekun** [comment]
Double-check the dataset name in `cfgs/dataset_configs/your_dataset_config` for any errors, this is all the advice I can provide.

**Comment by Everglowever** [comment]
In init.py,I didn't import the dataset.py
