### ISSUE TITLE
I ran into a problem

### ISSUE THREAD

**Issue by zjw102** [qizekun/ReCon#9]
When I run the program, I get the following error, is my data not downloaded, or my package is not installed？
![1690464568396](https://github.com/qizekun/ReCon/assets/107674802/c80289cf-581e-46b2-8c98-09cee6ad4a73)
Looking forward to your reply, thank you

**Comment by qizekun** [comment]
Hi!

It seems that the image failed to load properly.
Please check whether the metadata has been updated correctly like this [issue](https://github.com/qizekun/ReCon/issues/5#issuecomment-1579912892) and check whether the downloaded dataset path is correct.
Hope this can help you.
